using saturation code in stcal
spacetelescope/jwst pull request #6317
Opened 2021-08-30 13:58 UTC by cshanahan1

This PR changes saturation step to use the code now in stcal

2021-09-16 19:40 UTC, kmacdonald-stsci approved these changes

2021-09-16 20:04 UTC, jdavies-st requested changes
Looks good.  A comment below about code structure.  I liked how you broke out the IRS2 code into a separate function, which makes everything much more readable.  But I would just organize it a bit differently to make it clearer what each function does and make it also easier to test.

And it looks like the IRS2 mode code is not tested at all.  Would be good to write a unit test for that here.

2021-09-16 20:05 UTC, cshanahan1 commented on jwst/saturation/saturation_step.py
> +                sat = saturation.run_flag_saturated_pixels(input_model, ref_model)
@jdavies-st thanks for the feedback, lll make these changes! the tests for IRS2 mode are what i am working on currently, those will be up here shortly.

2021-09-29 15:28 UTC, jdavies-st approved these changes
Looks great!  🚀

2021-09-29 15:28 UTC, merged