separate and cache workflow jobs
spacetelescope/jwst pull request #6867
Opened 2022-05-31 16:42 UTC by zacharyburnett

Closes #
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)

**Description**

This PR addresses ...

Checklist
- [ ] Tests
- [ ] Documentation
- [ ] Change log
- [ ] Milestone
- [ ] Label(s)

2022-08-18 13:55 UTC, hbushouse commented
> JP-2157

2022-08-18 13:57 UTC, hbushouse commented
> Resolves [JP-2157](https://jira.stsci.edu/browse/JP-2157)

How does this fix JP-2157? Seems like this is strictly related to CI tests for PRs.

2022-08-18 13:58 UTC, zacharyburnett commented
> > Resolves [JP-2157](https://jira.stsci.edu/browse/JP-2157)
> 
> How does this fix JP-2157? Seems like this is strictly related to CI tests for PRs.

Oh whoops, that was accidental. I'll remove that

2022-08-22 09:31 UTC, jdavies-st commented
This looks nice.  Should really speed up the env setup.

One hiccup I recall in setting up CRDS caching to actually work between builds where the default context hadn't change was to make sure that the CRDS cache action is only happening when `pytest` is actually running.  If CRDS caching happens during code style checks or bandit, those don't actually pull any of the reffiles that the tests need, and because those jobs finish first, they produce the cache before the `pytest` runs do, leading to successful caching of precisely zero CRDS files.  Hopefully you can avoid that here.

2022-10-27 17:07 UTC, zacharyburnett commented
> One hiccup I recall in setting up CRDS caching to actually work between builds where the default context hadn't change was to make sure that the CRDS cache action is only happening when `pytest` is actually running. If CRDS caching happens during code style checks or bandit, those don't actually pull any of the reffiles that the tests need, and because those jobs finish first, they produce the cache before the `pytest` runs do, leading to successful caching of precisely zero CRDS files. Hopefully you can avoid that here.

@jdavies-st Does this apply to running `crds sync` on the latest context, like the following?
```shell
crds sync --contexts jwst_1009.pmap
```
It appears to be caching 438591 bytes at the moment

2022-10-27 17:08 UTC, zacharyburnett commented
I've also added a `workflow_dispatch:` that allows the unit testing workflow to be run from the web client using a specific CRDS context

2022-10-28 08:58 UTC, jdavies-st commented
You definitely don't want to use `crds sync`, because it will pull all items for that context.   And that's a lot of data. 100s of GB.

The way the CRDS caching should work is that workflow A runs the unit tests, pulling in all the CRDS reffiles it needs. At the end of the workflow, the state of the `crds_cache` directory should be cached, and that should be used for the next workflow.

The trick is to only github actions cache the workflows that actually run pytest on the whole suite of tests, otherwise you will cache nothing, and you will be restoring empty caches.  And make sure the cache key is something that changes occasionally but not too often, or it defeats the purpose of the caching.  You could have the key be the CRDS context, but I don't think that's a very good proxy for which CRDS reffiles change for the `jwst` unit tests.  I.e. the unit test reffiles are pretty stable, whereas CRDS context can change almost every day.  And even if the github actions cache is a bit out-of-date with the current state of the CRDS cache, that's not a problem as it will pull the new files over.  You could just hash the reference files in that dir (not the pmaps or rmaps) for a key.

2022-10-28 09:22 UTC, jdavies-st requested changes
I don't think this refactor is going to make the current problem of the failure of fetching CRDS reffiles, which then causes the workflows to fail.  This PR is not attached to any issue, but I assume that is the motivating factor?

What needs fixing is the github cache action setup - it should only run on jobs that run pytest on the full unit test suite, it should only populate the cache when run on push (merge PR) against master, and its key should be hashed from the contents of `$HOME/crds_cache/references`, i.e. the files that get pulled from CRDS to run these tests.

Note that PRs are always from forks, so in order for the cache to be used, it needs to be generated from the default branch on spacetelescope/jwst.  caches generated from branches on forks won't be used (security reasons).

All the other caching added in this PR on may speed up the build somewhat, but doesn't solve the above fundamental problem.  And caching the build state of dependencies might have a bunch of unintended consequences that we don't understand as well.  I would abide by the "if it's not broke, don't fix it" adage.

Finally, removing `tox` is actually a step backwards, as it is the only way that we locally can run tests exactly the same way they're run via Github actions.  This is an important middle layer that would be a shame to remove with better motivation.  I would highly recommend not removing `tox.ini`.

2022-10-28 09:22 UTC, jdavies-st commented on .github/workflows/ci.yml
> +        if: env.CRDS_CONTEXT != ''
I don't think you want to do this job.  Tunning `crds sync` will pull contexts over, but not actually do anything.  What you want cached are the CRDS reference files in `@HOME/crds_cache` that are actually used by the unit tests, a very, very small subset of the ~300GB snapshot of all CRDS reffiles.

2022-10-28 09:57 UTC, jdavies-st commented
The Github cache action was removed here

https://github.com/spacetelescope/jwst/pull/6165

It should be turned on again, making sure it only runs on jobs that run pytest, and it gets restored based on a hash of `$HOME/crds_cache/references`.  👍

2022-10-28 14:45 UTC, zacharyburnett commented
closing in favor of successor #7323

2022-10-28 14:45 UTC, closed without merging