Set DQ of ref pixels to DO_NOT_USE after refpix correction
spacetelescope/jwst pull request #7017
Opened 2022-09-02 12:31 UTC by jdavies-st

Closes #7015 

This PR addresses the current fragility of how reference pixels are set to DO_NOT_USE in `calwebb_detector1`.  Currently they rely on the GAIN reference file having zeros in the reference pixel locations, and then `ramp_fitting` sets those pixels to DO_NOT_USE in the science data DQ.

This PR sets the DQ of reference pixels to DO_NOT_USE at the end of the `refpix` step.  It does require that `DQInitStep` label these properly as REFERENCE_PIXELS, but this seems to be the case currently for the currently selected MASK reference files for all instruments.

Is this the best way to do this?  Thoughts?

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2024-09-23 17:29 UTC, zacharyburnett requested changes

2024-09-23 17:29 UTC, zacharyburnett commented on CHANGES.rst
> +
```suggestion
```

now that #8671 is merged (switching change log handling to `towncrier`) this change log entry should be a file in `changes/` instead:
```shell
echo "Set DQ of ref pixels to ``DO_NOT_USE`` after ``refpix`` correction" > changes/7017.refpix.rst
```

(new PRs will include instructions on how to do this)

2024-09-23 17:30 UTC, zacharyburnett commented on CHANGES.rst
> +
(ignore this if this PR is no longer active or needed)

2025-03-03 14:57 UTC, melanieclarke commented
I'm going to close this PR since it's now very out of sync with main.  

The issue is still tracked in [JP-3703](https://jira.stsci.edu/browse/JP-3703) and #7015.  If INS decides this change is desirable, we can make a new PR.

2025-03-03 14:57 UTC, closed without merging