fix definition of pixel ratio
spacetelescope/jwst pull request #7048
Opened 2022-09-16 20:29 UTC by cshanahan1

Fixes an error introduced by #7033 where the pixel scale ratio was incorrectly defined - it is now correctly computed as a ratio of pixel areas. 

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2022-09-16 20:36 UTC, mcara approved these changes
LGTM.

2022-09-16 20:40 UTC, mcara commented on CHANGES.rst
> +  ratio of input / output areas [#7048]
I think you could have simply appended 7048 to the line above: `... pixel scale ratio [#7033, #7048]`

2022-09-17 04:34 UTC, mcara commented
I do not believe failing tests are related to this PR.

2022-09-19 13:03 UTC, hbushouse requested changes
Found another error in the original PR that was merged. The changes implemented in terms of handling the drizpars reference file are now producing an error when the "get_reference_file" query to CRDS comes back with "N/A" (i.e. there's no drizpars ref file in CRDS applicable to the particular instrument+mode). The check for `ref_filename == 'N/A'` in line 87 of resample_step.py needs to be executed *before* the call to `get_drizpars` is made in line 83. If `get_drizpars` is called with a ref file name of "N/A", it throws an error.

2022-09-20 12:26 UTC, hbushouse commented on jwst/resample/resample_step.py
> +        	self.log.info('Using drizpars reference file: {}'.format(ref_filename))
The indent error here (too much indent) is causing code compilation to fail.

2022-09-20 12:26 UTC, hbushouse commented on jwst/resample/resample_step.py
> +        	self.log.info('Using drizpars reference file: {}'.format(ref_filename))
Since everything else appears to be correct, I'm going to go ahead and fix the error myself right in the PR branch, so that tests can be run.

2022-09-20 12:54 UTC, hbushouse commented
> I do not believe failing tests are related to this PR.

You can believe anything you want, but this was in fact leading to 2 different kinds of errors. One has been fixed, now I'm in the process of fixing the other. Always, always, always run a full regression test. Never rely on the built-in CI tests only.

2022-09-20 13:41 UTC, cshanahan1 commented
@hbushouse should i run the regression tests on this branch then before we merge?

2022-09-20 13:46 UTC, hbushouse commented
> @hbushouse should i run the regression tests on this branch then before we merge?

I did one run earlier this morning, which revealed the remaining error (having to do with initializing `self.wht_type`) and am about to kick off another run now that that problem has been fixed too in the code.

2022-09-20 14:58 UTC, hbushouse commented
Yay!  CI tests have passed and the full regtest run is clean: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/428/

I'm merging.

2022-09-20 14:59 UTC, hbushouse approved these changes
It's all good now.

2022-09-20 14:59 UTC, merged