use nightly wheels for `scipy` and `numpy`
spacetelescope/jwst pull request #7581
Opened 2023-05-08 15:07 UTC by zacharyburnett

Related to [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)

This PR ensures that `scipy`, and `numpy` are all built with nightly wheels against `main`

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2023-05-09 20:30 UTC, WilliamJamieson requested changes

2023-05-09 20:30 UTC, WilliamJamieson commented on requirements-dev.txt
> +scipy>=0.0.dev0
This change will not have any affect on the versions of `numpy` or `scipy` installed by `pip`. One needs to provide an alternate index for `pip` to search. See https://github.com/spacetelescope/romancal/pull/695#discussion_r1189078751 for details

2023-06-05 12:55 UTC, zacharyburnett commented on tox.ini
> +    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/scipy-wheels-nightly/simple
```suggestion
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
```

2023-06-26 20:01 UTC, nden approved these changes

2023-06-26 20:39 UTC, WilliamJamieson approved these changes

2023-06-26 21:01 UTC, nden commented
@zacharyburnett Please resolve conflicts and this is good to be erged.

2023-07-17 13:47 UTC, merged