enable dependabot
spacetelescope/jwst pull request #8004
Opened 2023-10-11 21:56 UTC by braingram

This PR adds a dependabot configuration file which should also enable dependabot to run on this repo.

The configuration file contains sections to keep both github actions versions up-to-date and upper pins for python dependencies (via pip) up-to-date.

I don't have access to the repository settings and I'm not sure if dependabot is enabled there as I found one old PR for jwst from dependabot:
https://github.com/spacetelescope/jwst/pull/6092

However it appears that at least the github actions are not being checked as an older version (3) of the checkout action is in use:
https://github.com/spacetelescope/jwst/blob/5c5b968e3c192b051c431ee8d42702e1c22a80ed/.github/workflows/publish-to-pypi.yml#L12

For an example of what to expect from dependabot PRs, here is the PR for asdf opened by dependabot to update the checkout action in that repository:
https://github.com/asdf-format/asdf/pull/1639

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2023-10-12 13:18 UTC, zacharyburnett requested changes
this looks great, thanks! I'm assuming the dependabot PRs ping the codeowners by default, but to keep @hbushouse from being spammed by PRs all the time, is there a way to make it ping me in addition / instead?

2023-10-12 13:42 UTC, braingram commented
Thanks for taking a look and good idea!

I think this should do it: ce3748f9227d3c75bc0d40ebd05538ce69b2fa4f

I added you as one of the [reviewers](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers). There is another option for [assignees](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#assignees) but reviewers seemed like a better fit. I've never used either option so we may just have to wait and see what the first PR looks like and adjust as needed.

2023-10-12 14:16 UTC, zacharyburnett approved these changes

2023-10-13 13:34 UTC, hbushouse approved these changes

2023-10-13 13:35 UTC, merged