Fix: models_grouped always return opened data models
spacetelescope/jwst pull request #8191
Opened 2024-01-12 05:49 UTC by mcara

`models_grouped` property of a `ModelContainer` should return file names instead of opened models when input are lists of files names under some circumstances. However, due to an incorrect indentation of a `if-block`, `models_grouped` *always* returns a list of opened (loaded in memory) data models.

This PR fixes the above.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2024-01-18 16:55 UTC, hbushouse requested changes

2024-01-18 16:55 UTC, hbushouse commented on CHANGES.rst
> +- Fixed a bug in the ``ModelContiner`` due to which ``models_grouped``
```suggestion
- Fixed a bug in the ``ModelContainer`` data model, due to which the ``models_grouped``
```

2024-01-18 16:56 UTC, hbushouse commented
Need to run a full regression test on the PR branch.

2024-02-10 22:11 UTC, mcara commented
Regression tests running here:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1200/

2024-02-15 16:26 UTC, hbushouse commented
> Regression tests running here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1200/

Regression test failures are benign and unrelated to this PR.

2024-02-15 17:53 UTC, hbushouse approved these changes

2024-02-15 17:53 UTC, merged