JP-3695: Clean up unnecessary copies
spacetelescope/jwst pull request #8676
Opened 2024-07-25 16:55 UTC by penaguerrero

Partially Resolves [JP-3695](https://jira.stsci.edu/browse/JP-3695)

Closes #

This PR addresses removing the unnecessary copies of all steps in the Detector1 pipeline. The same needs to be done for the stage2 pipelines.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2024-08-20 18:27 UTC, penaguerrero commented
reg tests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1656/

2024-09-20 14:12 UTC, tapastro requested changes
Some changes requested, and needs a changelog entry. We should be able to get this into the build!

The regression test will hopefully be replaced by benchmarks come the end of next build, but we can keep it in until they are functional.

2024-09-20 15:34 UTC, penaguerrero commented on jwst/emicorr/emicorr.py
> -            user_supplied_reffile - reference file supplied by the user
I removed this line already, not sure why it still showed up. I double checked now and it is not there.

2024-09-20 15:35 UTC, penaguerrero commented on jwst/ramp_fitting/ramp_fit_step.py
> -            input_model_W = copy.copy(input_model)
I reverted these lines.

2024-09-20 15:36 UTC, tapastro commented on jwst/emicorr/emicorr.py
> -            user_supplied_reffile - reference file supplied by the user
It's still listed in the documentation pages - that's where it also needs to be pulled.

2024-09-20 15:37 UTC, penaguerrero commented
> Some changes requested, and needs a changelog entry. 
We had talked about this in the meetings and had decided that no log entry was needed since it did not change the behavior for users. Thinking about it a bit more, I will go ahead and add a log entry, for tracking purposes.

2024-09-20 15:38 UTC, tapastro commented
> > Some changes requested, and needs a changelog entry.
>  We had talked about this in the meetings and had decided that no log entry was needed since it did not change the behavior for users. Thinking about it a bit more, I will go ahead and add a log entry, for tracking purposes.

That's fine, you can mark it with the appropriate no-changelog tag then.

2024-09-20 17:48 UTC, tapastro commented
Latest regtest run was clean: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1741/

Merging!

2024-09-20 17:48 UTC, merged