WIP JP-3664: Testing changes for numpy 2.0 compatibility
spacetelescope/jwst pull request #8718
Opened 2024-08-21 20:17 UTC by tapastro

Resolves [JP-3664](https://jira.stsci.edu/browse/JP-3664)

Closes #8580

This draft exists to remove jwst's upper pin on numpy, as well as provides a spot to test changes to coron3 unit tests that appear to be incompatible with np2.0.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

2024-09-20 18:58 UTC, melanieclarke commented
#8812 fixed most of the coron unit tests with numpy 2, but there's still one check that's barely out of spec on the Linux tests.

I think changing these lines to atol=1e-4, rtol=1e-5 should work:
https://github.com/spacetelescope/jwst/blob/217d6601083cb2e9de0440cc099afec77e405b9b/jwst/coron/tests/test_coron.py#L144-L145

2024-09-23 16:57 UTC, zacharyburnett requested changes

2024-09-23 16:57 UTC, zacharyburnett commented on CHANGES.rst
> +
```suggestion
```

now that #8671 is merged (switching change log handling to `towncrier`) this change log entry should be a file in `changes/` instead:
```shell
echo "Remove upper pin on ``numpy``" > changes/8718.general.rst
```

(new PRs will include instructions on how to do this)

2024-10-28 13:59 UTC, zacharyburnett commented
started a regtest: https://github.com/spacetelescope/RegressionTests/actions/runs/11555475241/job/32161141720

2025-01-10 21:07 UTC, tapastro commented
Reviving this PR, starting a fresh set of tests: https://github.com/spacetelescope/RegressionTests/actions/runs/12717188152

From comments on the JP ticket by David, I think we're ready to test and review this PR.

2025-01-13 14:27 UTC, melanieclarke commented
Regression test results look mostly as expected, but there is a unit test for extract_1d (marked 'slow', so it doesn't run in CI) that failed: jwst/extract_1d/tests/test_extract_1d_step.py::test_extract_niriss_soss_96.  I'm looking into it, but I haven't been able to reproduce it locally yet.

2025-01-13 18:08 UTC, kmacdonald-stsci approved these changes

2025-01-29 14:16 UTC, merged