allow python 3.13
spacetelescope/jwst pull request #8864
Opened 2024-10-08 12:36 UTC by braingram

Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)

Closes #

This PR addresses ...

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types) 
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
- ``changes/<PR#>.docs.rst``
- ``changes/<PR#>.stpipe.rst``
- ``changes/<PR#>.datamodels.rst``
- ``changes/<PR#>.scripts.rst``
- ``changes/<PR#>.fits_generator.rst``
- ``changes/<PR#>.set_telescope_pointing.rst``
- ``changes/<PR#>.pipeline.rst``

## stage 1
- ``changes/<PR#>.group_scale.rst``
- ``changes/<PR#>.dq_init.rst``
- ``changes/<PR#>.emicorr.rst``
- ``changes/<PR#>.saturation.rst``
- ``changes/<PR#>.ipc.rst``
- ``changes/<PR#>.firstframe.rst``
- ``changes/<PR#>.lastframe.rst``
- ``changes/<PR#>.reset.rst``
- ``changes/<PR#>.superbias.rst``
- ``changes/<PR#>.refpix.rst``
- ``changes/<PR#>.linearity.rst``
- ``changes/<PR#>.rscd.rst``
- ``changes/<PR#>.persistence.rst``
- ``changes/<PR#>.dark_current.rst``
- ``changes/<PR#>.charge_migration.rst``
- ``changes/<PR#>.jump.rst``
- ``changes/<PR#>.clean_flicker_noise.rst``
- ``changes/<PR#>.ramp_fitting.rst``
- ``changes/<PR#>.gain_scale.rst``

## stage 2
- ``changes/<PR#>.assign_wcs.rst``
- ``changes/<PR#>.badpix_selfcal.rst``
- ``changes/<PR#>.msaflagopen.rst``
- ``changes/<PR#>.nsclean.rst``
- ``changes/<PR#>.imprint.rst``
- ``changes/<PR#>.background.rst``
- ``changes/<PR#>.extract_2d.rst``
- ``changes/<PR#>.master_background.rst``
- ``changes/<PR#>.wavecorr.rst``
- ``changes/<PR#>.srctype.rst``
- ``changes/<PR#>.straylight.rst``
- ``changes/<PR#>.wfss_contam.rst``
- ``changes/<PR#>.flatfield.rst``
- ``changes/<PR#>.fringe.rst``
- ``changes/<PR#>.pathloss.rst``
- ``changes/<PR#>.barshadow.rst``
- ``changes/<PR#>.photom.rst``
- ``changes/<PR#>.pixel_replace.rst``
- ``changes/<PR#>.resample_spec.rst``
- ``changes/<PR#>.residual_fringe.rst``
- ``changes/<PR#>.cube_build.rst``
- ``changes/<PR#>.extract_1d.rst``
- ``changes/<PR#>.resample.rst``

## stage 3
- ``changes/<PR#>.assign_mtwcs.rst``
- ``changes/<PR#>.mrs_imatch.rst``
- ``changes/<PR#>.tweakreg.rst``
- ``changes/<PR#>.skymatch.rst``
- ``changes/<PR#>.exp_to_source.rst``
- ``changes/<PR#>.outlier_detection.rst``
- ``changes/<PR#>.tso_photometry.rst``
- ``changes/<PR#>.stack_refs.rst``
- ``changes/<PR#>.align_refs.rst``
- ``changes/<PR#>.klip.rst``
- ``changes/<PR#>.spectral_leak.rst``
- ``changes/<PR#>.source_catalog.rst``
- ``changes/<PR#>.combine_1d.rst``
- ``changes/<PR#>.ami.rst``

## other
- ``changes/<PR#>.wfs_combine.rst``
- ``changes/<PR#>.white_light.rst``
- ``changes/<PR#>.cube_skymatch.rst``
- ``changes/<PR#>.engdb_tools.rst``
- ``changes/<PR#>.guider_cds.rst``
</details>

2024-11-26 18:57 UTC, braingram commented
Blocked by https://github.com/spacetelescope/stcal/pull/300
(which is blocked by `scikit-image` not having a released version that supports 3.13)

2025-01-03 18:03 UTC, nden commented
It looks like the blocks have been resolved. Can you remove support for Python 3.10 and open this for review?

2025-01-03 18:54 UTC, nden commented
The failing test is fixed in #8965

2025-01-03 19:01 UTC, nden approved these changes
LGTM

2025-01-03 19:01 UTC, WilliamJamieson commented
Required CI will need to be updated once this is merged.

2025-01-03 20:03 UTC, braingram commented
Regression tests with python 3.13 show failures:
https://github.com/spacetelescope/RegressionTests/actions/runs/12602429376
Only some of these match the ones on main

2025-01-03 20:05 UTC, braingram commented
@WilliamJamieson would you update the title and description of this PR to reflect the changes?

2025-01-29 19:28 UTC, emolter requested changes
Removing support for 3.10 also requires us to bump the style checkers [here](https://github.com/spacetelescope/jwst/blob/689f7224f735f1c1cf555fbe521df3ee41306514/pyproject.toml#L277) and [here](https://github.com/spacetelescope/jwst/blob/689f7224f735f1c1cf555fbe521df3ee41306514/.ruff.toml#L15).  Feels a bit silly because these were just added today, but so it goes.

There are also two instances of the phrase

> JWST requires a C compiler for dependencies and is currently limited to Python 3.10, 3.11, or 3.12

in the docs, one in README.md and the other in install.rst that I think need to be changed.

2025-01-29 19:29 UTC, braingram commented
I'm closing this PR. It's attempting to do more than the description.

2025-01-29 19:29 UTC, closed without merging

2025-01-29 19:30 UTC, tapastro commented
Regression tests run today suprisingly show few issues - https://github.com/spacetelescope/RegressionTests/actions/runs/13037094545

It looks like there may have been a change in the workings of wfss background subtraction, but otherwise the differences are minimal.